# -*- coding: utf-8 -*-
"""GenAI_HuggingFace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_tJah2nnHs1Wzzjvjh_yYvKQOy-OXwX
"""

!pip install -q transformers gradio

from transformers import pipeline
import gradio as gr

classifier = pipeline("sentiment-analysis")

def analyze_text(text):
    result = classifier(text)[0]
    return f"Label: {result['label']}, Score: {round(result['score'], 4)}"

demo = gr.Interface(
    fn=analyze_text,
    inputs="text",
    outputs="text",
    title="My First AI Sentiment App",
    description="Type a sentence below to see if it's Positive or Negative!"
)

demo.launch(share=True)